spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/arogya_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          time_zone: Asia/Colombo

  jackson:
    serialization:
      indent_output: true
    time-zone: Asia/Colombo

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000ms # 10 minutes in milliseconds

server:
  port: 8080

jwt:
  secret-key: ${JWT_SECRET}
  expiration-time: 3600000 # 1 hour in milliseconds

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


